FROM node:9.11-alpine

WORKDIR /opt

RUN apk add -qU --no-cache -t .devstuff git \
    &&  git clone https://github.com/stellar/laboratory.git \
    &&  cd /opt/laboratory \
    &&  npm install \
    &&  apk del -q .devstuff
WORKDIR /opt/laboratory
COPY /laboratory/configure_network.sh .
RUN chmod +x configure_network.sh
EXPOSE 3000
ENTRYPOINT ./configure_network.sh
