FROM node:9.11-alpine

RUN apk add -qU --no-cache -t .build-deps git \
    &&  git clone https://github.com/stellar/laboratory.git /opt/laboratory \
    &&  cd /opt/laboratory \
    &&  npm install -s \
    &&  apk del -q .build-deps
WORKDIR /opt/laboratory
COPY ./laboratory/opt/laboratory/configure_network.sh .
EXPOSE 3000
ENTRYPOINT ./configure_network.sh
